spring.application.name=seguranca_comunitaria

# Conexao com o Banco de Dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/zelo_urbano
spring.datasource.username=postgres
spring.datasource.password=postgres

# Configuracoes do Hibernate / JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate

# Mostrar o SQL gerado no terminal
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true